// import { Json } from 'lib/database.types';

export type UserInfo = {
  about: string;
  age: number;
  alcohol: string;
  body: string;
  city: string;
  education: string;
  gender: string;
  goals: string[];
  horoscope: string;
  kids: string;
  length: string;
  name: string;
  smoke: string;
  sociotips: string;
};
export type UserPrefrences = {
  about: string;
  alcohol: string[];
  body: string[];
  education: string[];
  gender: string[];
  goals: string[];
  horoscope: string[];
  kids: string[];
  language: string[];
  maxAge: number;
  maxLength: number;
  minAge: number;
  minLength: number;
  smoke: string[];
  sociotips: string[];
};
export type User = {
  id: string;
  created_at: string;
  name: string;
  gender: string;
  age: string;
  interests: string[];
  user: UserInfo | null;
  search: UserPrefrences;
  avatar_image: { avatar: string; updated_at: string };
  cover_image: { cover: string; updated_at: string };
  sociotype: string;
  has_sociotype: boolean;
  updated_at: string;
  has_avatar: boolean;
  user_images?: string[];
};
